In [21]:
import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules

In [22]:
retail_shopping_basket = {
    'ID': [1, 2, 3, 4, 5, 6],
    'Basket': [
        ['Beer', 'Diaper', 'Pretzels', 'Chips', 'Aspirin'],
        ['Diaper', 'Beer', 'Chips', 'Lotion', 'Juice', 'BabyFood', 'Milk'],
        ['Soda', 'Chips', 'Milk'],
        ['Soup', 'Beer', 'Diaper', 'Milk', 'IceCream'],
        ['Soda', 'Coffee', 'Milk', 'Bread'],
        ['Beer', 'Chips']
    ]
}


retail = pd.DataFrame(retail_shopping_basket)
pd.options.display.max_colwidth = 60
print(retail)

   ID                                                Basket
0   1              [Beer, Diaper, Pretzels, Chips, Aspirin]
1   2  [Diaper, Beer, Chips, Lotion, Juice, BabyFood, Milk]
2   3                                   [Soda, Chips, Milk]
3   4                  [Soup, Beer, Diaper, Milk, IceCream]
4   5                           [Soda, Coffee, Milk, Bread]
5   6                                         [Beer, Chips]

In [23]:
retail_id = retail.drop('Basket', axis=1)
retail_basket = retail.Basket.str.join(',')
retail_basket

0              Beer,Diaper,Pretzels,Chips,Aspirin
1    Diaper,Beer,Chips,Lotion,Juice,BabyFood,Milk
2                                 Soda,Chips,Milk
3                  Soup,Beer,Diaper,Milk,IceCream
4                          Soda,Coffee,Milk,Bread
5                                      Beer,Chips
Name: Basket, dtype: object

In [24]:
retail_basket = retail_basket.str.get_dummies(',')
retail = retail_id.join(retail_basket)     
retail

,ID,Aspirin,BabyFood,Beer,Bread,Chips,Coffee,Diaper,IceCream,Juice,Lotion,Milk,Pretzels,Soda,Soup
0,1,1,0,1,0,1,0,1,0,0,0,0,1,0,0
1,2,0,1,1,0,1,0,1,0,1,1,1,0,0,0
2,3,0,0,0,0,1,0,0,0,0,0,1,0,1,0
3,4,0,0,1,0,0,0,1,1,0,0,1,0,0,1
4,5,0,0,0,1,0,1,0,0,0,0,1,0,1,0
5,6,0,0,1,0,1,0,0,0,0,0,0,0,0,0

In [25]:
retail_bool = retail.drop('ID', axis=1).astype(bool)
frequent_itemsets_2 = apriori(retail_bool, use_colnames=True)
frequent_itemsets_2

    support        itemsets
0  0.666667          (Beer)
1  0.666667         (Chips)
2  0.500000        (Diaper)
3  0.666667          (Milk)
4  0.500000   (Beer, Chips)
5  0.500000  (Beer, Diaper)

只考虑支持度(X>Y),[Beer,Chips]和[Beer,Diper]都很频繁，哪一种更相关？

In [26]:
association_rules(frequent_itemsets_2,metric='lift')

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(Beer),(Chips),0.666667,0.666667,0.5,0.75,1.125,0.055556,1.333333,0.333333
1,(Chips),(Beer),0.666667,0.666667,0.5,0.75,1.125,0.055556,1.333333,0.333333
2,(Beer),(Diaper),0.666667,0.500000,0.5,0.75,1.500,0.166667,2.000000,1.000000
3,(Diaper),(Beer),0.500000,0.666667,0.5,1.00,1.500,0.166667,inf,0.666667

结论：[Diaper，Beer]更相关